In [54]:
import pandas as pd

In [55]:
stats = pd.read_csv("player_mvp_stats.csv")

In [56]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.J. Green,SG,23,MIL,35,1,9.9,1.5,3.6,...,0.0,0.000,Milwaukee Bucks,58,24,0.707,0.0,116.9,113.3,3.61
1,1,Bobby Portis,PF,27,MIL,70,22,26.0,5.7,11.5,...,0.0,0.000,Milwaukee Bucks,58,24,0.707,0.0,116.9,113.3,3.61
2,2,Brook Lopez,C,34,MIL,78,78,30.4,6.1,11.5,...,0.0,0.000,Milwaukee Bucks,58,24,0.707,0.0,116.9,113.3,3.61
3,3,Giannis Antetokounmpo,PF,28,MIL,63,63,32.1,11.2,20.3,...,1000.0,0.606,Milwaukee Bucks,58,24,0.707,0.0,116.9,113.3,3.61
4,4,Goran Dragić,PG,36,MIL,58,0,15.0,2.4,5.8,...,0.0,0.000,Milwaukee Bucks,58,24,0.707,0.0,116.9,113.3,3.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10194,10194,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
10195,10195,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
10196,10196,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
10197,10197,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
10198,10198,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [57]:
del stats["Unnamed: 0"]

In [58]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          41
3P            0
3PA           0
3P%        1245
2P            0
2PA           0
2P%          82
eFG%         41
FT            0
FTA           0
FT%         401
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [59]:
stats[pd.isnull(stats["3P%"])][["Player","3PA"]]

                 Player  3PA
28           Guy Rucker  0.0
54          Chris Silva  0.0
109          Jeff Ayres  0.0
111      Kyrylo Fesenko  0.0
114        Lou Amundson  0.0
...                 ...  ...
10138   Jermaine O'Neal  0.0
10151  Hassan Whiteside  0.0
10171      JaVale McGee  0.0
10176       Malcolm Lee  0.0
10178      Nerlens Noel  0.0

[1245 rows x 2 columns]

In [60]:
stats[pd.isnull(stats["FT%"])][["Player","FTA"]]

             Player  FTA
18      A.J. Guyton  0.0
28       Guy Rucker  0.0
35       Ben Bentil  0.0
54      Chris Silva  0.0
73     Tyler Dorsey  0.0
...             ...  ...
10061   George King  0.0
10133  Trevor Keels  0.0
10141   Luke Zeller  0.0
10176   Malcolm Lee  0.0
10195   Steve Novak  0.0

[401 rows x 2 columns]

In [61]:
stats = stats.fillna(0)

In [62]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [63]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS']

In [64]:
train = stats[stats["Year"]<2024]

In [65]:
test = stats[stats["Year"]==2023]

In [66]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [67]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [68]:
predictions = reg.predict(test[predictors])

In [69]:
predictions = pd.DataFrame(predictions, columns = ["Predictions"], index=test.index)

In [70]:
predictions

       Predictions
0         0.002569
1         0.027583
2         0.033761
3         0.201353
4        -0.001882
...            ...
10129    -0.017183
10130     0.003451
10131    -0.011556
10132     0.012755
10133     0.013843

[539 rows x 1 columns]

In [71]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [72]:
combination

                      Player  Share  Predictions
0                 A.J. Green  0.000     0.002569
1               Bobby Portis  0.000     0.027583
2                Brook Lopez  0.000     0.033761
3      Giannis Antetokounmpo  0.606     0.201353
4               Goran Dragić  0.000    -0.001882
...                      ...    ...          ...
10129      Mitchell Robinson  0.000    -0.017183
10130             Obi Toppin  0.000     0.003451
10131         Quentin Grimes  0.000    -0.011556
10132             RJ Barrett  0.000     0.012755
10133           Trevor Keels  0.000     0.013843

[539 rows x 3 columns]

In [73]:
combination.sort_values("Share", ascending = False).head(10)

                       Player  Share  Predictions
9966              Joel Embiid  0.915     0.189934
482              Nikola Jokić  0.674     0.178313
3       Giannis Antetokounmpo  0.606     0.201353
1941             Jayson Tatum  0.280     0.135906
945   Shai Gilgeous-Alexander  0.046     0.135657
9158         Donovan Mitchell  0.030     0.079280
3034         Domantas Sabonis  0.027     0.096830
66                Luka Dončić  0.010     0.184948
4842            Stephen Curry  0.005     0.108264
7353             Jimmy Butler  0.003     0.100781

In [74]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["Predictions"])

0.002590842083407408

In [75]:
combination["Share"].value_counts()

Share
0.000    526
0.001      2
0.606      1
0.010      1
0.674      1
0.046      1
0.280      1
0.002      1
0.027      1
0.005      1
0.003      1
0.030      1
0.915      1
Name: count, dtype: int64

In [76]:
actual = combination.sort_values("Share", ascending=False)
predicted = combination.sort_values("Predictions", ascending=False)

In [77]:
actual["Rk"] = list(range(1,actual.shape[0]+1))
predicted["Predicted_Rk"] = list(range(1,predicted.shape[0]+1))

In [78]:
actual.merge(predicted, on="Player").head(5)

,Player,Share_x,Predictions_x,Rk,Share_y,Predictions_y,Predicted_Rk
0,Joel Embiid,0.915,0.189934,1,0.915,0.189934,2
1,Nikola Jokić,0.674,0.178313,2,0.674,0.178313,4
2,Giannis Antetokounmpo,0.606,0.201353,3,0.606,0.201353,1
3,Jayson Tatum,0.280,0.135906,4,0.280,0.135906,6
4,Shai Gilgeous-Alexander,0.046,0.135657,5,0.046,0.135657,7

In [79]:
combination.head(10)

                  Player  Share  Predictions
0             A.J. Green  0.000     0.002569
1           Bobby Portis  0.000     0.027583
2            Brook Lopez  0.000     0.033761
3  Giannis Antetokounmpo  0.606     0.201353
4           Goran Dragić  0.000    -0.001882
5          Grayson Allen  0.000    -0.000856
6            Jae Crowder  0.000     0.001845
7           Jevon Carter  0.000    -0.008636
8             Joe Ingles  0.000     0.001567
9           Jrue Holiday  0.000     0.055028

In [80]:
combination.sort_values("Share", ascending = False).head(10)

                       Player  Share  Predictions
9966              Joel Embiid  0.915     0.189934
482              Nikola Jokić  0.674     0.178313
3       Giannis Antetokounmpo  0.606     0.201353
1941             Jayson Tatum  0.280     0.135906
945   Shai Gilgeous-Alexander  0.046     0.135657
9158         Donovan Mitchell  0.030     0.079280
3034         Domantas Sabonis  0.027     0.096830
66                Luka Dončić  0.010     0.184948
4842            Stephen Curry  0.005     0.108264
7353             Jimmy Butler  0.003     0.100781

In [81]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("Predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return sum(ps) / len(ps)

In [82]:
ap = find_ap(combination)

In [83]:
ap # error metric, 1 would be perfect

0.8261904761904761

In [84]:
years = list(range(2003,2024))

In [85]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [86]:
sum(aps) / len(aps)

0.7627495808929632

In [87]:
def add_ranks(combination):
    combination = combination.sort_values("Share", ascending = False)
    combination["Rk"] = list(range(1,combination.shape[0]+1))
    combination = combination.sort_values("Predictions", ascending = False)
    combination["Predicted_Rk"] = list(range(1,combination.shape[0]+1))
    combination["Diff"] = combination["Rk"] - combination ["Predicted_Rk"]
    return combination

In [88]:
ranking = add_ranks(all_predictions[1])
ranking[ranking["Rk"]<6].sort_values("Diff", ascending = False)

             Player  Share  Predictions  Rk  Predicted_Rk  Diff
6732     Chris Paul  0.159     0.151306   5             2     3
4245   LeBron James  0.969     0.169640   1             1     0
9594    Dwyane Wade  0.562     0.143627   3             3     0
6284  Dwight Howard  0.271     0.116754   4             4     0
1246    Kobe Bryant  0.577     0.096205   2            10    -8

In [89]:
def backtest(stats,model,year,predictors):
    aps = []
    all_predictions = []
    for year in years[5:]:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = reg.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
    
        all_predictions.append(combination)
        aps.append(find_ap(combination))

    return sum(aps)/len(aps), aps, pd.concat(all_predictions)

In [90]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [91]:
mean_ap

0.7627495808929632

In [92]:
all_predictions[all_predictions["Rk"]<5].sort_values("Diff").head(10)

               Player  Share  Predictions  Rk  Predicted_Rk  Diff
9248      Joakim Noah  0.258     0.043877   4            34   -30
1260      Kobe Bryant  0.487     0.072063   3            14   -11
5377      Kobe Bryant  0.873     0.086022   1            12   -11
5408      Kobe Bryant  0.291     0.059798   4            15   -11
726      Devin Booker  0.216     0.084623   4            14   -10
6654     Kevin Durant  0.495     0.080671   2            11    -9
1076      Paul George  0.352     0.118208   3            11    -8
3941  Carmelo Anthony  0.393     0.073885   3            11    -8
1246      Kobe Bryant  0.577     0.096205   2            10    -8
5390      Kobe Bryant  0.354     0.081569   4            11    -7

In [93]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)],axis=1).sort_values(0,ascending=False)

           0     1
13  0.056538  eFG%
29  0.038029  W/L%
18  0.033007   DRB
17  0.022029   ORB
4   0.010494    FG
25  0.009863   PTS
21  0.009669   STL
20  0.007493   AST
22  0.006872   BLK
15  0.004312   FTA
8   0.004212   3PA
10  0.003477    2P
12  0.003037   2P%
30  0.000298    GB
1   0.000087     G
27  0.000056     W
2   0.000025    GS
0   0.000010   Age
32 -0.000025  PA/G
28 -0.000338     L
31 -0.000480  PS/G
26 -0.000682  Year
33 -0.000726   SRS
14 -0.001131    FT
23 -0.003437   TOV
24 -0.003612    PF
3  -0.003616    MP
11 -0.005829   2PA
16 -0.007058   FT%
9  -0.007954   3P%
5  -0.008711   FGA
7  -0.015850    3P
19 -0.026046   TRB
6  -0.109630   FG%

In [94]:
stat_ratios = stats[["PTS","AST","STL","BLK","3P","Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [95]:
stat_ratios

                 PTS       AST       STL       BLK        3P  Year
Year
2003 18     0.000000  0.560870  0.743572  0.000000  0.000000   1.0
     19     0.687980  0.280435  0.743572  5.765086  0.000000   1.0
     20     2.828362  1.065653  1.338429  1.153017  1.933371   1.0
     21     0.930047  1.794784  1.189715  0.000000  1.208357   1.0
     22     0.611538  0.560870  0.446143  0.230603  0.725014   1.0
...              ...       ...       ...       ...       ...   ...
2023 10129  0.811285  0.435028  1.476263  4.707424  0.000000   1.0
     10130  0.811285  0.483365  0.492088  0.523047  1.312418   1.0
     10131  1.238854  1.015066  1.148205  1.046094  2.221015   1.0
     10132  2.148808  1.353421  0.656117  0.523047  1.716239   1.0
     10133  0.109633  0.000000  0.000000  0.000000  0.302866   1.0

[10199 rows x 6 columns]

In [96]:
stat_ratios = stat_ratios.reset_index(drop=True)

# Now you can assign the values to the stats DataFrame
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [97]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R
0,A.J. Green,SG,23,MIL,35,1,9.9,1.5,3.6,0.424,...,0.707,0.0,116.9,113.3,3.61,0.000000,0.560870,0.743572,0.000000,0.000000
1,Bobby Portis,PF,27,MIL,70,22,26.0,5.7,11.5,0.496,...,0.707,0.0,116.9,113.3,3.61,0.687980,0.280435,0.743572,5.765086,0.000000
2,Brook Lopez,C,34,MIL,78,78,30.4,6.1,11.5,0.531,...,0.707,0.0,116.9,113.3,3.61,2.828362,1.065653,1.338429,1.153017,1.933371
3,Giannis Antetokounmpo,PF,28,MIL,63,63,32.1,11.2,20.3,0.553,...,0.707,0.0,116.9,113.3,3.61,0.930047,1.794784,1.189715,0.000000,1.208357
4,Goran Dragić,PG,36,MIL,58,0,15.0,2.4,5.8,0.421,...,0.707,0.0,116.9,113.3,3.61,0.611538,0.560870,0.446143,0.230603,0.725014

In [98]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [99]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [100]:
mean_ap

0.7520181768803093

In [101]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes

In [102]:
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [103]:
stats["Pos"].unique()

array(['SG', 'PF', 'C', 'PG', 'SF', 'PG-SG', 'PF-SF', 'SG-PG', 'PF-C',
       'SG-SF', 'SF-PF', 'SF-SG', 'C-PF', 'SG-PF', 'PG-SF', 'SG-PG-SF',
       'SF-C'], dtype=object)

In [104]:
stats["NTm"].value_counts()

NTm
34    355
6     354
15    354
13    349
16    348
7     347
32    346
14    344
0     343
11    342
30    342
26    342
12    341
17    341
33    339
23    337
1     337
29    334
4     333
25    333
28    333
10    330
9     330
8     329
27    326
18    325
24    256
2     202
22    179
19    159
3     157
5     147
20    143
31     90
21     32
Name: count, dtype: int64

In [105]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators = 300, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[5:], predictors)

In [106]:
mean_ap

0.8061895477888125

In [107]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [108]:
mean_ap

0.7520181768803093

In [109]:
players = pd.read_csv("players.csv")

In [110]:
# Filter the data for the year 2023
players_2023 = players[players["Year"] == 2023]

In [111]:
players_2023

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
12664,0,1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,...,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2,2023
12665,1,2,Steven Adams,C,29,MEM,42,42,27.0,3.7,...,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6,2023
12666,2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,...,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4,2023
12667,3,4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,...,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9,2023
12668,4,5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,...,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13363,699,535,Thaddeus Young,PF,34,TOR,54,9,14.7,2.0,...,1.3,1.8,3.1,1.4,1.0,0.1,0.8,1.6,4.4,2023
13364,700,536,Trae Young,PG,24,ATL,73,73,34.8,8.2,...,0.8,2.2,3.0,10.2,1.1,0.1,4.1,1.4,26.2,2023
13365,701,537,Omer Yurtseven,C,24,MIA,9,0,9.2,1.8,...,0.9,1.7,2.6,0.2,0.2,0.2,0.4,1.8,4.4,2023
13366,702,538,Cody Zeller,C,30,MIA,15,2,14.5,2.5,...,1.7,2.6,4.3,0.7,0.2,0.3,0.9,2.2,6.5,2023
13367,703,539,Ivica Zubac,C,25,LAC,76,76,28.6,4.3,...,3.1,6.8,9.9,1.0,0.4,1.3,1.5,2.9,10.8,2023

In [112]:
from sklearn.linear_model import Ridge
numeric_predictors = [
    'Age', 'G', 'GS', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%',
    'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
    'Year'
]

train = stats[stats["Year"]<2024]
reg = Ridge(alpha=0.1)

# Train the Ridge regression model
reg.fit(train[numeric_predictors], train["Share"])

Ridge(alpha=0.1)

In [114]:
mvp_predictions = reg.predict(stats[stats["Year"] == 2023][numeric_predictors])

In [115]:
players_2023 = stats[stats["Year"] == 2023]  # Filter players for the year 2023

In [116]:
predictions_df = pd.DataFrame({"Player": players_2023["Player"], "MVP_Prediction": mvp_predictions})

In [117]:
predictions_df

                      Player  MVP_Prediction
0                 A.J. Green       -0.013442
1               Bobby Portis        0.019507
2                Brook Lopez        0.026318
3      Giannis Antetokounmpo        0.165761
4               Goran Dragić       -0.007898
...                      ...             ...
10129      Mitchell Robinson       -0.009031
10130             Obi Toppin        0.000881
10131         Quentin Grimes       -0.003283
10132             RJ Barrett        0.014660
10133           Trevor Keels        0.013281

[539 rows x 2 columns]

In [118]:
predictions_df = predictions_df.sort_values("MVP_Prediction", ascending = False)

In [119]:
predictions_df.head(10) # using reg

                       Player  MVP_Prediction
9966              Joel Embiid        0.175811
3       Giannis Antetokounmpo        0.165761
66                Luka Dončić        0.162415
482              Nikola Jokić        0.161090
7673             Kevin Durant        0.152143
5784           Damian Lillard        0.143939
945   Shai Gilgeous-Alexander        0.133764
8587          Zion Williamson        0.131785
1941             Jayson Tatum        0.118196
6054            Anthony Davis        0.117237

In [120]:
rf.fit(train[predictors], train["Share"])

RandomForestRegressor(min_samples_split=5, n_estimators=300, random_state=1)

In [121]:
players_2023_filtered = stats[stats["Year"] == 2023][predictors]

In [122]:
mvp_predictions = rf.predict(players_2023_filtered)

In [123]:
predictions_df_rf = pd.DataFrame({
    "Player": stats[stats["Year"] == 2023]["Player"],
    "MVP_Prediction_RF": mvp_predictions
})

In [124]:
predictions_df_rf = predictions_df_rf.sort_values(by="MVP_Prediction_RF", ascending=False)
predictions_df_rf = predictions_df_rf.reset_index(drop=True)
predictions_df_rf.index += 1

In [125]:
top_predictions_rf = predictions_df_rf.head(10)

In [126]:
top_predictions_rf

                     Player  MVP_Prediction_RF
1               Joel Embiid           0.734966
2     Giannis Antetokounmpo           0.621986
3              Nikola Jokić           0.501252
4              Jayson Tatum           0.374904
5              Jaylen Brown           0.179038
6          Donovan Mitchell           0.112338
7   Shai Gilgeous-Alexander           0.112002
8               Luka Dončić           0.087197
9            Damian Lillard           0.086418
10         Domantas Sabonis           0.067657

In [127]:
top_predictions_rf.to_csv("final_predictions_2023.csv")

In [128]:
players_2007_filtered = stats[stats["Year"] == 2007][predictors]
mvp_predictions = rf.predict(players_2007_filtered)
predictions_df_rf = pd.DataFrame({
    "Player": stats[stats["Year"] == 2007]["Player"],
    "MVP_Prediction_RF": mvp_predictions
})
predictions_df_rf = predictions_df_rf.sort_values(by="MVP_Prediction_RF", ascending=False)
predictions_df_rf = predictions_df_rf.reset_index(drop=True)
predictions_df_rf.index += 1
top_predictions_rf = predictions_df_rf.head(10)
top_predictions_rf

             Player  MVP_Prediction_RF
1     Dirk Nowitzki           0.603781
2        Steve Nash           0.588472
3       Kobe Bryant           0.273516
4        Tim Duncan           0.214980
5      LeBron James           0.160055
6     Tracy McGrady           0.085570
7       Dwyane Wade           0.062722
8          Yao Ming           0.046261
9   Carmelo Anthony           0.045145
10   Gilbert Arenas           0.036293

In [168]:
years = list(range(2003, 2024))

import os
output_folder = "mvp_predictions"
os.makedirs(output_folder, exist_ok=True)

# Create an empty DataFrame to store top predictions
top_predictions_rf = pd.DataFrame(columns=["Year", "Player", "MVP_Prediction_RF"])

# Iterate through each year
for year in years:
    
    # Filter the data for the current year
    players_filtered = stats[stats["Year"] == year][predictors]

    # Make predictions using the Random Forest model
    mvp_predictions = rf.predict(players_filtered)

    # Create a DataFrame with predictions for the current year
    predictions_df_rf = pd.DataFrame({
        "Year": [year] * len(players_filtered),  # Add the current year
        "Player": stats[stats["Year"] == year]["Player"],
        "MVP_Prediction_RF": mvp_predictions,

    })

    # Sort the predictions by MVP_Prediction_RF and reset the index
    predictions_df_rf = predictions_df_rf.sort_values(by="MVP_Prediction_RF", ascending=False)
    predictions_df_rf = predictions_df_rf.reset_index(drop=True)
    predictions_df_rf.index += 1

    # Store only the top 10 predictions
    top_10_predictions = predictions_df_rf.head(10)

    # Remove the "Year" column from the DataFrame
    top_10_predictions = top_10_predictions.drop("Year", axis=1)

    # Concatenate the top predictions for the current year with the result DataFrame
    top_predictions_rf = pd.concat([top_predictions_rf, top_10_predictions])

    file_path = os.path.join(output_folder, f"{year}_predictions.csv")

    # Save the top 10 predictions to a CSV file for the current year
    top_10_predictions.to_csv(file_path, index=False)


top_10_predictions

C:\Users\Love\AppData\Local\Temp\ipykernel_18184\375948657.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  top_predictions_rf = pd.concat([top_predictions_rf, top_10_predictions])

                     Player  MVP_Prediction_RF
1               Joel Embiid           0.734966
2     Giannis Antetokounmpo           0.621986
3              Nikola Jokić           0.501252
4              Jayson Tatum           0.374904
5              Jaylen Brown           0.179038
6          Donovan Mitchell           0.112338
7   Shai Gilgeous-Alexander           0.112002
8               Luka Dončić           0.087197
9            Damian Lillard           0.086418
10         Domantas Sabonis           0.067657